# fly.toml app configuration file generated for prosto-travel-bot on 2025-05-31T19:31:23+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'prosto-travel-bot'
primary_region = 'iad'

[deploy]
  strategy = "immediate"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
